# Generated by Django 4.1.7 on 2023-03-28 15:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_order_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='download',
        ),
        migrations.AddField(
            model_name='product',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
    ]
