# Generated by Django 4.1.7 on 2023-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_download_orderitem_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='download',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='download',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
