# Generated by Django 4.1.7 on 2023-03-28 17:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
    ]
