# Generated by Django 4.1.7 on 2023-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='id',
        ),
        migrations.AddField(
            model_name='friend',
            name='_id',
            field=models.AutoField(default=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='name_of_friend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
