# Generated by Django 4.1.7 on 2023-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_friend_friend_id_remove_friend_id_friend__id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
